// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import domain "github.com/bxcodec/go-clean-arch-grpc/domain"
import mock "github.com/stretchr/testify/mock"

// ArticleRepository is an autogenerated mock type for the ArticleRepository type
type ArticleRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *ArticleRepository) Delete(id int64) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: cursor, num
func (_m *ArticleRepository) Fetch(cursor string, num int64) ([]domain.Article, error) {
	ret := _m.Called(cursor, num)

	var r0 []domain.Article
	if rf, ok := ret.Get(0).(func(string, int64) []domain.Article); ok {
		r0 = rf(cursor, num)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Article)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int64) error); ok {
		r1 = rf(cursor, num)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *ArticleRepository) GetByID(id int64) (domain.Article, error) {
	ret := _m.Called(id)

	var r0 domain.Article
	if rf, ok := ret.Get(0).(func(int64) domain.Article); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Article)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByTitle provides a mock function with given fields: title
func (_m *ArticleRepository) GetByTitle(title string) (domain.Article, error) {
	ret := _m.Called(title)

	var r0 domain.Article
	if rf, ok := ret.Get(0).(func(string) domain.Article); ok {
		r0 = rf(title)
	} else {
		r0 = ret.Get(0).(domain.Article)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: a
func (_m *ArticleRepository) Store(a *domain.Article) error {
	ret := _m.Called(a)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Article) error); ok {
		r0 = rf(a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: article
func (_m *ArticleRepository) Update(article *domain.Article) error {
	ret := _m.Called(article)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Article) error); ok {
		r0 = rf(article)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
